version: '2.1'
networks:
  app-tier:
    driver: bridge

services:

  springboot:
    image: springboot-drivers
    restart: always
    build: ./
    environment: 
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/drivers
    ports: 
      - '9080:9080'
    expose: 
      - '9080'
    depends_on: 
      - 'kafka'
      - 'db'
    links: 
      - 'kafka'
      - 'db'
    networks:
      - app-tier

  zookeeper:
    image: 'bitnami/zookeeper:3'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier

  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
      - '29092:29029'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://0.0.0.0:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_SERVER_PORT=9092
      - KAFKA_CREATE_TOPICS=driver_location:1:1
    depends_on:
      - "zookeeper"
    links:
      - zookeeper
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 4
    networks:
      - app-tier

  db:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_DATABASE: 'drivers'
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'root'
      # You can use whatever password you like
      # MYSQL_PASSWORD: 'user123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'user1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    depends_on:
      - "kafka"
    links:
      - kafka
    networks:
      - app-tier

# Names our volume
volumes:
  my-db:
    