server:
  port: 9080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drivers
    username: root
    password: user1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers:
      - localhost:9092
      - kafka:9092
      - kafkaContainer:9092
    consumer:
      auto-offset-reset: latest
      max-poll-records: 100